SMD-Bioinformatics-Lund/nextflow_wgs

- CHANGELOG.md
- bin/create_yml.pl
- main.nf
Updates for create_yml.pl. It should now be easier to add specific scout specifications into yamlfile depending on input from nextflow pipeline. Needs to go live for PARP_inhib somatic pipeline to work properly.
> Yaml fixes

- configs/nextflow.hopper.config
- main.nf
Gens load command for middleman added to generate_gens_data process. 
Expected behaviour: Creates a textfile in cron-dir on hopper with instructions for middleman to load data into GENS.
Test: File generated on hopper /fs1/results/cron/gens/GIAB-210618.gens , can it be successfully loaded into GENS.
> Gens middleman

- configs/nextflow.hopper.config
- main.nf
Added a panel depth analysis for oncogenetic samples.
> added panel depth for onco

- main.nf
Added small snippet to load new data into future loqusdb instance.
> loqusdb for wgs devel, load double

- CHANGELOG.md
- bin/create_yml.pl
- configs/nextflow.hopper.config
Small edits, minor patch.
Fixed some file paths and correct access-dirs for myeloid profile
> small needed myeloid fixes, no manual editing of scout yaml

- CHANGELOG.md
- configs/nextflow.hopper.config
Small patch, with updated genes to unaccredited workflow. Input data has been tested and does not break pipeline.
DMD and FGF14
Pushing to live
> Add expansionhunter genes

- CHANGELOG.md
- configs/nextflow.hopper.config
- main.nf
Move out hard-coded resources from main.nf
Final changes
> Move out hard-coded resources

- CHANGELOG.md
- configs/nextflow.hopper.config
- main.nf
MELT configuration has been reworked to further facilitate better recalls. Firstly, known variants that melt previously have called have been added to a priors-list to help guide MELT callling. This is recommended by MELT developers. Second, exome flag was added to signify that input data is not WGS. Third, cov flag was removed as it was incorrectly used as standard deviation of insert size, instead by removing this flag the default values are used, which are recommended by developers (it is what was used during training of MELT).
To confirm the changed all previously called insert-elements for 25 samples were run using the new configs and resulted in 100% recall.
Verification report has …
> Melt exome priors ignorecontigs

- configs/nextflow.hopper.config
Added the latest variant_catalog for expansionhunter/reviewer/stranger (https://github.com/Clinical-Genomics/reference-files/pull/71). It has been tested and Sofie has viewed the results (in scout and reviewer plots). According to her it looks as it should.
Latest hg38 variant catalog file from https://github.com/Clinical-Genomics/reference-files/pull/71 is replacing the previous catalogue, 7 STRs has been removed and 4 new ones has been added.
1. Step 1
2. Step 2
- Reviewer 1: Name1, (\@Github\_handle1)  
- Reviewer 2: Name1,  (\@Github\_handle2)
- ...
- Name, (\@Github\_handle)
- ...
> Added the latest variant_catalog 

- .github/workflows/changelog-reminder.yml
- CHANGELOG.md
Add a changelog reminder github workflow that blocks PRs until changelog is updated 🖤
To skip the check, apply `skip-changelog-reminder` label to the PR prior to creating the request.
This update does not affect the pipeline whatsoever.
> Add changelog reminder github workflow

- CHANGELOG.md
- bin/create_yml.pl
What is changed? What is the result of the changes?
fixes # (issue)
1. create_yml.pl for a myeloid-const sample should produce a yaml without images and with owner myeloid
- Reviewer 1: Alexander @alkc 
- Alexander @alkc
> myeloid-const fixes to match clarity reanalysis

- CHANGELOG.md
- main.nf
Add CRON file for loading Chanjo2
fixes # (issue)
- Reviewer 1: Viktor Henmyr (@ViktorHy )  
- ...
- Jakob Willforss (@Jakob37 )
- ...
> Chanjo2 middleman

- CHANGELOG.md
- bin/create_yml.pl
- main.nf
What is changed? What is the result of the changes?
fixes # (issue)
1. Step 1
2. Step 2
- Reviewer 1: Viktor Henmyr (@ViktorHy )  
- Jakob Willforss, (@Jakob37 )
> D4 in yaml

- .github/pull_request_template.md
- CHANGELOG.md
Trimming the checklist to make it more concise and adding a point to log what samples were used for testing.
Can be previewed here how it will look: 
https://github.com/Clinical-Genomics-Lund/nextflow_wgs/blob/jw/trim_template/.github/pull_request_template.md
fixes # (issue)
1. Step 1
2. Step 2
- Reviewer 1: Name1, (\@Github\_handle1)  
- Reviewer 2: Name1,  (\@Github\_handle2)
- ...
- Name, (\@Github\_handle)
- ...
> Trim checklist template and add validation samples

- CHANGELOG.md
- main.nf
> D4 full coverage

- CHANGELOG.md
- bin/create_yml.pl
- configs/nextflow.hopper.config
- main.nf
Close #162 
Clean copy of the PR #82 
> Mody CF (clean)

- CHANGELOG.md
- configs/nextflow.hopper.config
- main.nf
> Disable Chanjo2

- CHANGELOG.md
- configs/nextflow.hopper.config
Re-enable d4 file generation for Chanjo2, as it seems it will get some action after all.
> Enable Chanjo2

- CHANGELOG.md
- configs/nextflow.hopper.config
- main.nf
Resource optimizations. Increased/decreased memory and cpu usage acording to last years trace files. This has been done for both wgs and onco profiles
Added a parameter reanalyze, that is set by bjorn when a sample is rerun. This is to avoid multiple additions of same individuals to loqusdb
> Optimizations 202407

- CHANGELOG.md
- main.nf
Hotifx for bugged if-statement in annotsv-process
Full run of affected sample documented
> annotsv if-statement fixes

- CHANGELOG.md
- bin/create_yml.pl
> reverted some code changes for create_yml.pl

- CHANGELOG.md
- main.nf
> Fixing vep_sv issue in vcf files with no variants

- CHANGELOG.md
- bin/create_yml.pl
- main.nf
> Stable yaml and versions

- CHANGELOG.md
- bin/create_yml.pl
- main.nf
Close #273 
After adding error checking to create_yml it does not allow dev assays.
Here an assay type "dev" is added containing all sub-analysis types.
If running ol' wgs with the `--dev` flag the assay is assigned `dev` and the dev profile is used.
> Create yml dev assay

- CHANGELOG.md
- configs/nextflow.hopper.config
Routine update of the bed intersect file. File is updated from Trannel.
Close #283 
> Update bed intersect

- CHANGELOG.md
- main.nf
> Include --case-id flag in Gens command

- CHANGELOG.md
- main.nf
Fix crashes on top-up samples.
fixes #298 
> Hotfix - fix pipeline not matching `.fq.gz` as fastq.gz

- CHANGELOG.md
- scripts/deploy_hopper.sh
`workflow/annotate_snvs.nf` not covered by hopper deploy script. this patch fixes that.
> Add workflow dir to deploy script

- CHANGELOG.md
- main.nf
Fixed output file name
Such a minor thing, should have been caugt by just running one myeloid_const sample
> correct output file name

- CHANGELOG.md
- main.nf
> Manta runtime
