SMD-Bioinformatics-Lund/nextflow_wgs

deploy_hopper_dev.sh, main.nf
Moved normalize and split multi to before instersect.
Add vcfsortstream | vcfuniq
and added -u flag to intersect to avoid duplicate indel variants in vcf
=> norm_split before intesect, uniqified

CHANGELOG.md, main.nf
BAM files not multiplied by 5 through locuscollector out-channel.
=> bam file needed for dedup taken from bwa, not locuscollector

bin/cnv2bed.pl
Changes color code from rgb(0,64,255) to rgb(0,0,153) and also removes features thickStart, thickEnd and strand orientation. Changes are made to accommodate a better visualisation in ChAS.
=> Changed color and line thickness in bin/cnv2bed.pl

.gitignore, CHANGELOG.md, bin/reference_tools/update_bed.pl, bin/reference_tools/vcf2.pm, configs/nextflow.hopper.config, main.nf
tool to update bed-file
fetches ensembl build gtf and extracts relevant regions (exonic regions of coding genes)
merges with old agilent exome
adds non-overlapping clinvar-variants to bed file and logs what variants were added since last version of clinvar and which were removed
To test:
./update_bed.pl --old /data/bnf/ref/annotations_dbs/clinvar38_20200106.vcf.gz --new /fs1/resources/ref/hg38/annotation_dbs/clinvar38_latest.vcf.gz --clinvardate 20221129 --build 108
=> tool to update bed-file with new ensembl builds and clinvar-updates

main.nf
Use bcftools instead of vcfbreakmulti to split variants in split_normalize_mito process.
=> fix för split_normalize_mito

CHANGELOG.md, bin/merge_melt.pl, main.nf
Disabled filtering of INTRONIC/null/PROMOTER variants from melt-vcf. Instead do intersection with bedtools against designbed. Will only remove unwanted regions and keep relevant.
Before we would miss out on rare splice-site variants.
I also added publishdirs for the unfiltered merged-melt-vcf and for the intersected
=> Fix melt slice variants

CHANGELOG.md, main.nf
Increased amount of reads melt can use in RAM. Process already under-utilize RAM by far. Average mem peak below 10GB increasing should just yield more consistent calling and remove a lot of randomness.
=> Increase melt sens

configs/nextflow.hopper.config
Added a profile for masked hg38 reference. This update includes WGS references build with this new genome build for GATK and has passed validation. Future updates to GENS PoN needs to be done once this has been in production for a month or so
Tests needs to be passed:
Oncov1-0 sample [V]
Oncov2-0 sample [V]
WGS sample trio [V]
WGS sample single [V]
WGS is tested fully into Scout via validation and onco profiles does not need to be tested for scout import.
=> hg38 masked genome build and GATK references

CHANGELOG.md, main.nf
Minimal patch on the now merged stub-PR.
I updated the final CRON log dir to instead of being hard coded using the "results" dir as base.
This works as long as you specify the results dir within the config. But if you would like to use the `--outdir` argument in the run nextflow command, then it does no longer work.
Here is the logic:
* `resultsdir` - specified within the config only (`/fs1/results` for production)
* `outdir` - this is by default `resultsdir` + `devsuffix`, but can be specified in the `runnextflow.pl` runscript as an argument
* `crondir` - is `outdir` + "cron"
This PR updates the final log file to be written to a path specified by `crondir` + "logs" rather than `resultsdir` + "/cron/log"
I have successfully done stubruns and a test run.
It would be valuable to get an …
=> Fixing the final log dir

.github/pull_request_template.md, CHANGELOG.md
Add new type of change to this PR template: `documentation`.
Updates to documentation external to code source are exempted from code review/stub runs.
Might still be good idea to do a test run of the pipeline when commenting code, say because of some whitespace error straight from hell.
closes #108 
- Reviewer 1: Jakob, @Jakob37 
- ...
=> Add `documentation` to type of change section in PR template

CHANGELOG.md, configs/nextflow.hopper.config
The updated intersect file is produced as described below. I also placed a `CHANGELOG` file in the same folder for future travelers.
We decided to update the config to point directly to the new file rather than the "active" as a way to document it.
We might automate the generation of this file in the same way the clinvar file (on which it is based) is updated.
We talked about bunching together this update with the updates for Sentieon and VEP.
```
perl update_bed.pl --old clinvar38_20221129.vcf --new clinvar38_20231230.vcf --build 108 --clinvardate 20231230
```
Diff result:
```
clinvar in common between versions :249890
added new(unique targets)          :49276(1159)
removed old(unique targets)        :3471(21)
```
Close #123 
* Minor change
can be loaded …
=> Update intersect file

CHANGELOG.md, bin/prescore_sv.pl
Genmod expects an int and won't process it otherwise
fixes #170 
Small change to `prescore_sv.pl` that always casts GATK GQC vals as ints.
- Patch
A plot of GQC against the caller-penalty rank score component can be of help here.
- Reviewer 1: Viktor, @ViktorHy 
- ...
- Alex, @alkc
=> GATK GQC always cast to int to prevent genmod from ignoring it

CHANGELOG.md, bin/filter_mutect2_mito.pl
This is a change to make mitochondrial variants loadable by loqusdb. Loqusdb requires a genotype quality field. 
1. In the split_normalize_mito step, use the ${group}.mutect2.breakmulti.filtered5p.0genotyped.vcf
2. Run the updated filter_mutect2_mito.pl as usual
The GQ field should be added to all filtered variants
=> Added GQ to format field of all individuals via filter_mutect2

CHANGELOG.md, main.nf
Fixes #219, fixes #137
`bqsr_bam_choice` input channel is modified before let loose to the actual `bqsr` process. 
Sample id and group id positions are switched in the input tuple, matching the order defined in the process input block.
It's a dirty workaround, but I'm prioritizing getting this fixed quickly over sorting out the sample id, group id order in the processes preceding bsqr.
=> Fix sample_id and group_id positions in bqsr_bam_choice tuples

CHANGELOG.md, bin/create_yml.pl, main.nf
In this PR I aim to fix two issues.
First, eklipse images from trios would always be random, or rather the image that was created last in the pipeline, To fix this I have added proband ID information to create_yaml process in main.nf and use that information in create_yml.pl to select correct image.
Second, some genelist would go missing without any reason from yaml-files. I tracked the issue down to a crappy regex that matched anything with *test* and ignored them. This resulted in missing all intestinal genelists. I removed the regex-part and cleaned up the code around genelist a bit.
Moreover, I also changed some variable names to be more readable, removed some errors and made sure to only output to STDERR.
=> Fix createyml random image matching

CHANGELOG.md, bin/save-active-scout-gene-panels-to-json.py, configs/nextflow.hopper.config
This update changes the scout.gene_panel JSON path to a reduced JSON that only contains the data for active gene panels, thereby fixing the addition of dead/removed gene panels to our scout yaml files.
The reduced JSON is just a collection of panels filtered on the fields `hidden` and `is_archived`.
The new JSON is generated by a new script on lennart and added to the worker crontab with the same settings as the old gene panel back up script.
In short, it fetches the most recent versions of all gene panels in our scout production gene_panel collection, keeps all that are not hidden or archived, and saves a JSON of reduced panel objects (keeping only panel_name, institute, version and _id).
```
/data/bnf/scripts/save-active-scout-gene-panels.py
```
The update removes the following list of …
=> Add new gene_panel JSON to avoid adding removed gene panels to our scout YAMLs

CHANGELOG.md, main.nf
fixes https://github.com/Clinical-Genomics-Lund/nextflow_wgs/issues/216
=> Fix inconsistent order of VCFs to SVDB merge between reruns of wgs trios

CHANGELOG.md, bin/cnv2bed.pl
Fixes #277 
`cnv2bed.pl` uses regex match that extracts rank scores, expecting integers. however, since the merge of #247 the rank scores are encoded as floats, which breaks the rank score threshold filter
this patch adjusts the regex to also catch floats.
=> correctly match floating point rank scores

CHANGELOG.md, main.nf
A process is added that symlinks input bams under a dummy filename and emits the symlink to copy_bam. This allows copy_bam to do its work and emit the copied bam files under the original filename.
This _partially_ resolves #306 , but will still not fix rerunning samples with renamed bams. Please see original issue for more info on how to fix this the proper way.
=> Add rename_bam workaround for copy_bam process

CHANGELOG.md, main.nf
Correct export of environment variable THEANO_FLAGS for postprocess gatk. No need for review
=> theano flag correctly set for postprocess gatk
